### ISSUE TITLE
Clarification: Tractus-X EDC Chart usage

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/knowledge-agents-edc#24]
The [Helm Charts](https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/main/charts) currently contained in this repo seem to be at least an almost complete copy of the [Tractus-X EDC Charts](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/charts). 

If this is the case, at least a mention in the `NOTICE.md` of the original source is necessary. 

What I am wondering though is, if the Chart could be pulled as regular dependency. If there are other images used for knowledge-agents, then just overwriting them via `values.yaml` could still be achieved, but the risk of both Charts getting out of sync is mitigated.

So if the Charts are a (nearly) copy, I would suggest to switch to using a dependency instead of copy/pasting the code

relevant for #17

**Comment by drcgjung** [comment]
the structure of the dataplane section is different (we allow several data planes of which one or several could be agent planes) -> this cannot be reached through dependencies alone because the original charts only support a single data plane.

I have the reference placed into the README.md is that ok?

**Comment by SebastianBezold** [comment]
Ah ok understood. Maybe it is ok like it is right now then.
A reference to the original source could still be valuable though for maintenance reasons.

But this issue is solved with your explanation
